### ISSUE TITLE
Duration does not update in example code

### ISSUE THREAD

**Issue by robbeman** [cristijora/vue2-transitions#1]
There is a small "bug" in your example page (http://vuejs.creative-tim.com/vue2-transitions/).

When changing the duration the example code does not update immediately when the "group" toggle is on, but when you switch from group to simple and back to group it does include the duration in the example code.

![image](https://user-images.githubusercontent.com/3245659/34555025-004e16d6-f130-11e7-821f-58a1e898bfad.png)

(Additionally, the trigger button does not do anything for groups. Maybe you should disable it to avoid "confusion". Or maybe you can replace it with the "add" button. Just a suggestion.)

**Comment by cristijora** [comment]
Thanks for the feedback @robbeman and for the nice suggestion.
Updated the demo. Trigger changes to add item and the code should update properly now.
